server:
  port: 8081
  address: 0.0.0.0
  servlet:
    session:
      cookie:
        max-age: 2592000
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: apicloud
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  session:
    timeout: 2592000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/apicloud?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  jackson:
    default-property-inclusion: non_null
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  data:
    redis:
      port: 6379
      host: 127.0.0.1
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
mybatis-plus:
  type-aliases-package: bupt.edu.jhc.apicloud.model.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
knife4j:
  enable: true
  setting:
    language: zh_cn
apicloud:
  client:
    gateway-host: localhost:8090

dubbo:
  application:
    name: dubbo-springboot-provider
    enable-file-cache: false
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848