server:
  port: 8090
spring:
  application:
    name: gateway
  data:
    redis:
      port: 6379
      host: 127.0.0.1
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: qi-api-interface
          uri: http://localhost:8082
          predicates:
            - Path=/api/**
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
dubbo:
  application:
    qosEnable: false
    enable-file-cache: false
    name: dubbo-springboot-consumer
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848