server:
  port: 8090
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: qi-api-interface
          uri: http://localhost:8082
          predicates:
            - Path=/api/**